### ISSUE TITLE
[Q] Can we make context settings dynamic?

### ISSUE THREAD

**Issue by zaigham** [SEDAdigital/XRouting#27]
For exmaple, site_url: instead of using `http://site.com/de/` we could use `[[++http_host]][[++base_url]]` ?

**Comment by christianseel** [comment]
We could do that inside XRouting, however this could also raise issues in other extras (or even the core?) since they might not parse the placeholders… This would need be clarified.

**Comment by goldsky** [comment]
`{server_protocol}://{http_host}{base_url}`

**Comment by zaigham** [comment]
@goldsky does it work this way?

**Comment by goldsky** [comment]
Yes, babel.virtudraft.com uses this.

**Comment by christianseel** [comment]
See goldsky post: https://github.com/SEDAdigital/XRouting/issues/27#issuecomment-266396488 👍
