### ISSUE TITLE
Both domains showing 404 errors

### ISSUE THREAD

**Issue by rudymurillojr** [SEDAdigital/XRouting#29]
I built my site using ModX and it's been working flawlessly. I decided to build a new site and manage it with the same installation of ModX. I'm using [b]Xrouting[/b] for this.

I went ahead and pointed my domain2 (laredomusicawards.com) to the ModX install directory... Checked that it was pointing to domain1 (sldgtv.com) and it was.

I then installed Xrouting.

Then I created my new context with the following settings:

<img src="https://s20.postimg.org/gxlwsqkn1/Screen_Shot_2017_02_28_at_1_06_04_PM.png"/>

Now both domains show a 404 error.

Then I tried this same thing on another ModX install and it worked. The only difference with this install is I didn't have Friendly URLs on (yet) and I hadn't renamed the ht.acces file.

Any ideas what it could be? What am I doing wrong?

**Comment by christianseel** [comment]
Hi! Should be nothing with friendly URLs. Did you double check the `xrouting.include_www` system setting depending on your domains? Besides that I'd have no spontaneous idea what's going wrong on your site.
