### ISSUE TITLE
Freezing/timeout loop with 2 contexts and subfolders

### ISSUE THREAD

**Issue by LudvikMichalek** [SEDAdigital/XRouting#31]
I'm trying to create 2 context with leading "www" on hostnames, with "include_www" setting turned off.

The contexts are "web" and "intranet", but when I try to access "intranet" I am getting some kind of loop or timeout in MODX (2.5.7), which causes the intranet never load.

When using hte debug feature, the debug information shows correct routes and everything is perfectly fast, but when outside of debug mode, the site freezes and the intranet never loads. See the attached screenshot of all context/settings:

![issue](https://user-images.githubusercontent.com/1345993/30282486-bb548444-9715-11e7-88c1-a673bca6403d.png)

Any idea here, what might be wrong?

**Comment by christianseel** [comment]
Hi @LudvikMichalek, those settings look perfectly fine to me. Since the debugging stuff is working and the XRouting plugin does nothing else after the Debugging output, I assume that there is a different problem with your intranet integration/content/snippets/whatever, but there's no problem with XRouting.

**Comment by christianseel** [comment]
For debugging purpose I'd recommend disabling all other plugins AND snippets and just have basic static content in your contexts. Than it should work…

**Comment by LudvikMichalek** [comment]
Thanks for your response and support! I have guessed the same now, so I start disabling plugins etc. I have suspicion on one of my own snippets that might be in conflict with that. Maybe also Login extra might be in conflict, since I need the user to be logged into the context before he accesses the route on the **intranet** context.
