### ISSUE TITLE
[Q] Would there be any issues redirecting to a context with a base_url of just "/" ?

### ISSUE THREAD

**Issue by jonleverrier** [SEDAdigital/XRouting#33]
Hope you don't mind me asking this question here...happy to close this ticket if you don't have time to answer:

I have a working setup based on your guide here...
https://modx.today/posts/2015/05/using-xrouting-for-multilingual-websites-in-modx

I was wondering, if I don't want `/en/` in the `base_url` for my english context, would this cause issues with the way Xrouting works?

So rather than `domain.com > domain.com/en/` I just get `domain.com > domain.com`?

I have this working, I just wanted to see if there might be potential issues with this approach?

**Comment by christianseel** [comment]
Hey, you just need to make sure that each context has a unique `http_host`+`base_url` combination so there are no conflicts.
