### ISSUE TITLE
xrouting_contextmap.cache.php contains contexts limited to the user who triggered the refresh

### ISSUE THREAD

**Issue by garethparker** [SEDAdigital/XRouting#34]
Using xrouting to host 11 contexts on a single install. Each context is a subdomain of the main domain.

XRouting seems to have been working fine for several months, however recently we've been having issues where some contexts will not be accessible and will return the error page for the default context. When this happens the main context will still be listed in the cache file, along with one of the other 10 contexts.

We believe this could be down to us defining that users within the mgr context only have access to two contexts: the main context and the context they have context permissions to access.

To temporarily fix this we've commented out the 'OnSiteRefresh' event within the plugin, but not sure if there's something that needs changing in the plugin, or if context access permissions need to be set differently for the plugin to work?

**Comment by christianseel** [comment]
Hi @garethparker, this should be related to ACL / permissions and not the number of contextes. XRouting v1 does need contexts without ACLs. However there's XRouting v2 which is in 'beta' (but we already run it in various production instances for months without issues).

So feel free to take a look into the `2.0.0` branch and update your plugin and upload the files to `/core/components/xrouting/…`!

Let me know if that solves your issue!

**Comment by garethparker** [comment]
@christianseel that fixed it, 2.0 looks good! Thanks
